"""upgrade table clientes

Revision ID: 15fd0081f214
Revises: e9f3a2831ed4
Create Date: 2024-03-28 22:06:29.322807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15fd0081f214'
down_revision = 'e9f3a2831ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('cliente_direccion', sa.String(), nullable=True))
    op.drop_column('client', 'clienteDireccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('clienteDireccion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'cliente_direccion')
    # ### end Alembic commands ###
