"""Add sample_type_name

Revision ID: 1f7e73f956ad
Revises: 3ae4689971c0
Create Date: 2024-06-13 19:09:35.945987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7e73f956ad'
down_revision = '3ae4689971c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_coding', sa.Column('sample_type_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_coding', 'sample_type_name')
    # ### end Alembic commands ###
