"""coding update

Revision ID: 3ae4689971c0
Revises: c55f9f7a4fc0
Create Date: 2024-05-31 21:44:05.825984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae4689971c0'
down_revision = 'c55f9f7a4fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
