"""Added initial table

Revision ID: 6c3e2a4ec338
Revises: f99b017c78db
Create Date: 2024-05-26 14:50:49.965846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c3e2a4ec338'
down_revision = 'f99b017c78db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patient', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_patient_client_patient_id', table_name='patient')
    op.drop_column('patient', 'client_patient_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('client_patient_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_patient_client_patient_id', 'patient', ['client_patient_id'], unique=False)
    op.alter_column('patient', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
