"""remove sampletypename

Revision ID: 6dc601ae45d7
Revises: 1f7e73f956ad
Create Date: 2024-06-15 14:15:42.276385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc601ae45d7'
down_revision = '1f7e73f956ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_coding', 'sample_type_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_coding', sa.Column('sample_type_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
