"""Added initial table

Revision ID: b524471b130d
Revises: 1b3226667bb5
Create Date: 2024-03-27 20:33:51.666632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b524471b130d'
down_revision = '1b3226667bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient', 'direccion')
    # ### end Alembic commands ###
