"""Added initial table

Revision ID: c55f9f7a4fc0
Revises: 18b3afe39e25
Create Date: 2024-05-28 22:16:57.341142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55f9f7a4fc0'
down_revision = '18b3afe39e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_result', 'coding_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analysis_result', 'coding_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
