"""Added relation

Revision ID: c7a240e00b17
Revises: c84683d857e8
Create Date: 2024-06-29 18:21:25.927994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a240e00b17'
down_revision = 'c84683d857e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
