"""Added relation

Revision ID: c84683d857e8
Revises: 6dc601ae45d7
Create Date: 2024-06-28 18:52:27.194381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c84683d857e8'
down_revision = '6dc601ae45d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
