"""update tableclient

Revision ID: e9f3a2831ed4
Revises: d866501641d0
Create Date: 2024-03-28 21:17:27.252186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f3a2831ed4'
down_revision = 'd866501641d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('clienteDireccion', sa.String(), nullable=True))
    op.drop_column('client', 'cliente_direccion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('cliente_direccion', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('client', 'clienteDireccion')
    # ### end Alembic commands ###
