"""Add limites

Revision ID: f8b9c065d254
Revises: bd303c9b8ed3
Create Date: 2024-05-28 21:19:25.015038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b9c065d254'
down_revision = 'bd303c9b8ed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_coding', sa.Column('sample_type_uid', sa.String(), nullable=True))
    op.create_foreign_key(None, 'analysis_coding', 'sample_type', ['sample_type_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'analysis_coding', type_='foreignkey')
    op.drop_column('analysis_coding', 'sample_type_uid')
    # ### end Alembic commands ###
